# Generated by Django 5.0.3 on 2026-09-28 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argomento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('livello', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzato', 'Avanzato')], default='principiante', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Argomenti',
                'ordering': ['titolo'],
            },
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('livello', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzato', 'Avanzato')], default='principiante', max_length=20)),
                ('orario', models.TimeField(help_text='Orario della lezione')),
                ('anno_accademico', models.CharField(default='2025/2026', help_text='Anno accademico (es. 2025/2026)', max_length=20)),
                ('gruppo_whatsapp', models.CharField(blank=True, default='', help_text='ID o nome del gruppo WhatsApp del corso (es. 123456@g.us)', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Corsi',
                'ordering': ['scuola__nome', 'livello'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField(help_text='Testo del messaggio con eventuali placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Scuola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('sede', models.CharField(max_length=300)),
                ('gruppo_whatsapp', models.CharField(blank=True, default='', help_text='ID o nome del gruppo WhatsApp della scuola (es. 123456@g.us)', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Scuole',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Allievo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(choices=[('leader', 'Leader'), ('follower', 'Follower'), ('both', 'Entrambi')], default='leader', max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('recensione', models.CharField(choices=[('si', 'Sì'), ('no', 'No')], default='no', max_length=2)),
                ('livello', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzato', 'Avanzato')], default='principiante', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_prospect', models.BooleanField(default=False, help_text='Se True, è un prospect (non ancora iscritto a un corso)')),
                ('note', models.TextField(blank=True, default='', help_text='Note aggiuntive (usato principalmente per prospect)')),
                ('corso', models.ForeignKey(blank=True, help_text='Corso di appartenenza (vuoto per prospect)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allievi', to='core.corso')),
            ],
            options={
                'verbose_name_plural': 'Allievi',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Jolly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priorita', models.PositiveIntegerField(default=1, help_text='1 = priorità più alta')),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jolly_entries', to='core.allievo')),
            ],
            options={
                'verbose_name_plural': 'Jolly',
                'ordering': ['priorita'],
            },
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('argomento', models.ForeignKey(blank=True, help_text='Argomento trattato nella lezione', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lezioni', to='core.argomento')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lezioni', to='core.corso')),
            ],
            options={
                'verbose_name_plural': 'Lezioni',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rotation', models.BooleanField(default=False, help_text='True se questa persona è in rotazione a causa di disparità numerica')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_matches', to='core.allievo')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_matches', to='core.allievo')),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.lezione')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Generato', max_length=50)),
                ('rendered_text', models.TextField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lezione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lezione')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.messagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importo', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('trimestre', models.CharField(choices=[('T1', 'Primo Trimestre'), ('T2', 'Secondo Trimestre'), ('T3', 'Terzo Trimestre')], default='T1', max_length=2)),
                ('data_pagamento', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='core.allievo')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='core.corso')),
            ],
            options={
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(default='0', help_text='Giorni della settimana (0=Lun, 6=Dom) separati da virgola', max_length=50)),
                ('time', models.TimeField(help_text='Ora inizio evento')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rsvp_days_before', models.IntegerField(default=0)),
                ('rsvp_time', models.TimeField(default='08:00:00')),
                ('match_days_before', models.IntegerField(default=0)),
                ('match_time', models.TimeField(default='19:00:00')),
                ('rsvp_mode', models.CharField(choices=[('POLL', 'Sondaggio (Default)'), ('LLM', 'Risposta Libera (Gemini AI)')], default='POLL', max_length=10)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('debug_mode', models.BooleanField(default=True)),
                ('corso', models.ForeignKey(blank=True, help_text='Corso a cui si applica la schedulazione (vuoto se globale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.corso')),
            ],
        ),
        migrations.AddField(
            model_name='corso',
            name='scuola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corsi', to='core.scuola'),
        ),
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presente', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='core.allievo')),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='core.lezione')),
            ],
            options={
                'verbose_name_plural': 'Presenze',
                'unique_together': {('lezione', 'allievo')},
            },
        ),
    ]
