# Generated by Django 5.0.3 on 2026-09-28 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenza',
            name='fonte',
            field=models.CharField(choices=[('manuale', 'Manuale'), ('whatsapp', 'WhatsApp')], default='manuale', max_length=20),
        ),
        migrations.CreateModel(
            name='SondaggioMattutinoConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('testo', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondaggi', to='core.corso')),
            ],
        ),
    ]
