# Generated by Django 5.0.3 on 2026-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presenza_fonte_sondaggiomattutinoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='giorno_settimana',
            field=models.CharField(choices=[('Lunedi', 'Lunedi'), ('Martedi', 'Martedi'), ('Mercoledi', 'Mercoledi'), ('Giovedi', 'Giovedi'), ('Venerdi', 'Venerdi'), ('SABATO', 'Sabato'), ('DOMENICA', 'Domenica')], default='Lunedi', max_length=15),
        ),
    ]
