# Generated by Django 5.0.3 on 2026-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corso_giorno_settimana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='giorno_settimana',
            field=models.CharField(choices=[('LUNEDI', 'Lunedì'), ('MARTEDI', 'Martedì'), ('MERCOLEDI', 'Mercoledì'), ('GIOVEDI', 'Giovedì'), ('VENERDI', 'Venerdì'), ('SABATO', 'Sabato'), ('DOMENICA', 'Domenica')], default='LUNEDI', max_length=15),
        ),
    ]
