# Generated by Django 5.0.3 on 2026-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_corso_giorno_settimana'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezione',
            name='titolo',
            field=models.CharField(blank=True, default='', help_text='Titolo o convenzione (es. 1/12 - 1° Trimestre)', max_length=200),
        ),
    ]
