# Generated by Django 5.0.3 on 2026-09-29 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lezione_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='allievo',
            name='partner',
            field=models.OneToOneField(blank=True, help_text="Partner di ballo dell'allievo", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.allievo'),
        ),
    ]
