# Generated by Django 5.0.3 on 2026-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_allievo_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenza',
            name='is_jolly',
            field=models.BooleanField(default=False, help_text='Se True, è presente alla lezione come Jolly'),
        ),
    ]
