# Generated by Django 5.0.3 on 2026-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_presenza_is_jolly'),
    ]

    operations = [
        migrations.AddField(
            model_name='allievo',
            name='in_gruppo_scuola_whatsapp',
            field=models.BooleanField(default=False, help_text="Indica se l'allievo è presente nel gruppo WhatsApp della Scuola"),
        ),
    ]
