# Generated by Django 5.0.3 on 2026-09-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_allievo_in_gruppo_corso_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sondaggiomattutinoconfig',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='sondaggiomattutinoconfig',
            name='giorni_settimana',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='Giorni della settimana (0=Lun, 1=Mar, 2=Mer, 3=Gio, 4=Ven, 5=Sab, 6=Dom) separati da virgola', max_length=50),
        ),
        migrations.AddField(
            model_name='sondaggiomattutinoconfig',
            name='is_poll',
            field=models.BooleanField(default=True, help_text='Se True invia un sondaggio nativo WhatsApp con opzioni Sì/No, altrimenti messaggio di testo.'),
        ),
        migrations.AddField(
            model_name='sondaggiomattutinoconfig',
            name='orario',
            field=models.CharField(default='08:00', help_text='Orario invio demone nel formato HH:MM (es. 08:00)', max_length=5),
        ),
        migrations.AddField(
            model_name='sondaggiomattutinoconfig',
            name='poll_opzione_1',
            field=models.CharField(default='Ci sono! 🕺💃', max_length=100),
        ),
        migrations.AddField(
            model_name='sondaggiomattutinoconfig',
            name='poll_opzione_2',
            field=models.CharField(default='Non ci sono 🚫', max_length=100),
        ),
        migrations.AddField(
            model_name='sondaggiomattutinoconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sondaggiomattutinoconfig',
            name='corso',
            field=models.ForeignKey(blank=True, help_text='Corso specifico, oppure vuoto per impostazione globale predefinita', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sondaggi', to='core.corso'),
        ),
        migrations.AlterField(
            model_name='sondaggiomattutinoconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se attivo, il demone invierà automaticamente il sondaggio secondo la schedulazione.'),
        ),
        migrations.AlterField(
            model_name='sondaggiomattutinoconfig',
            name='testo',
            field=models.TextField(default="Buongiorno ragazzi! 🕺💃 Vi ricordiamo che oggi c'è lezione per il corso {corso} alle {orario}.\nChi di voi sarà presente stasera? Rispondete al sondaggio per confermare la vostra presenza!"),
        ),
    ]
